from __future__ import annotations

import base64
import hashlib
import hmac
import secrets
import struct
import time
from io import BytesIO
from urllib.parse import quote


def generate_totp_secret() -> str:
    """Return a compact Base32 secret suitable for authenticator apps."""
    return base64.b32encode(secrets.token_bytes(20)).decode("ascii").rstrip("=")


def _normalize_secret(secret: str | None) -> bytes:
    text = (secret or "").strip().replace(" ", "").upper()
    padding = "=" * ((8 - len(text) % 8) % 8)
    return base64.b32decode(text + padding, casefold=True)


def _hotp(secret: str, counter: int, digits: int = 6) -> str:
    key = _normalize_secret(secret)
    msg = struct.pack(">Q", int(counter))
    digest = hmac.new(key, msg, hashlib.sha1).digest()
    offset = digest[-1] & 0x0F
    code = struct.unpack(">I", digest[offset:offset + 4])[0] & 0x7FFFFFFF
    return str(code % (10 ** digits)).zfill(digits)


def current_totp(secret: str, period: int = 30, digits: int = 6) -> str:
    return _hotp(secret, int(time.time()) // period, digits=digits)


def verify_totp(secret: str | None, code: str | None, period: int = 30, window: int = 1, digits: int = 6) -> bool:
    if not secret or not code:
        return False
    cleaned = "".join(ch for ch in str(code) if ch.isdigit())
    if len(cleaned) != digits:
        return False
    now_counter = int(time.time()) // period
    try:
        return any(hmac.compare_digest(_hotp(secret, now_counter + offset, digits=digits), cleaned) for offset in range(-window, window + 1))
    except Exception:
        return False


def provisioning_uri(username: str, secret: str, issuer: str = "Передача") -> str:
    label = quote(f"{issuer}:{username}")
    return f"otpauth://totp/{label}?secret={secret}&issuer={quote(issuer)}&algorithm=SHA1&digits=6&period=30"


def qr_svg_data_uri(value: str) -> str:
    """Return a scannable QR code as a self-contained data URI.

    Primary path returns PNG via python-qrcode/Pillow. If Pillow or PNG
    rendering is unavailable on the server, fall back to a pure SVG QR
    generated by the same qrcode package. The account page should never
    show a blank “QR-code unavailable” block when the QR library is present.
    """
    data = (value or "").strip()
    if not data:
        return ""

    try:
        import qrcode

        qr = qrcode.QRCode(
            version=None,
            error_correction=qrcode.constants.ERROR_CORRECT_M,
            box_size=8,
            border=3,
        )
        qr.add_data(data)
        qr.make(fit=True)
        img = qr.make_image(fill_color="#111827", back_color="white")
        if hasattr(img, "convert"):
            img = img.convert("RGB")
        buffer = BytesIO()
        img.save(buffer, format="PNG")
        encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
        return f"data:image/png;base64,{encoded}"
    except Exception:
        pass

    try:
        import qrcode
        import qrcode.image.svg

        img = qrcode.make(data, image_factory=qrcode.image.svg.SvgPathImage)
        buffer = BytesIO()
        img.save(buffer)
        encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
        return f"data:image/svg+xml;base64,{encoded}"
    except Exception:
        return ""
